on: [push, pull_request]
name: build
jobs:
  build:
    name: Cabal Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.3
      - run: cabal build
